-- MySQL Script generated by MySQL Workbench
-- Thu Dec  9 12:18:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

#SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
#SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
#SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Final_Project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Final_Project` ;

-- -----------------------------------------------------
-- Schema Final_Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Final_Project` DEFAULT CHARACTER SET utf8mb4 ;
USE `Final_Project` ;
SET AUTOCOMMIT = 0; SET FOREIGN_KEY_CHECKS = 0; SET UNIQUE_CHECKS = 0;
-- -----------------------------------------------------
-- Table `Final_Project`.`AUTHOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`AUTHOR` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`AUTHOR` (
  `AUTHOR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `AUTHOR_NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`AUTHOR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`KNOWN_CHARACTERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`KNOWN_CHARACTERS` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`KNOWN_CHARACTERS` (
  `CHARACTER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CHARACTER_NAME` VARCHAR(50) NOT NULL,
  `CHARACTER_ANOMALY` INT(11) NULL DEFAULT NULL,
  `CHARACTER_AUTHOR` INT(11) NOT NULL,
  PRIMARY KEY (`CHARACTER_ID`),
  #INDEX `CHARACTER_AUTHOR` (`CHARACTER_AUTHOR` ASC) VISIBLE,
  CONSTRAINT `KNOWN_CHARACTERS_ibfk_1`
    FOREIGN KEY (`CHARACTER_AUTHOR`)
    REFERENCES `Final_Project`.`AUTHOR` (`AUTHOR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`CONTAIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`CONTAIN` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`CONTAIN` (
  `CONTAIN_CLASS` VARCHAR(30) NOT NULL,
  `CONTAIN_DESCRIPT` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`CONTAIN_CLASS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`RISK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`RISK` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`RISK` (
  `RISK_CLASS` VARCHAR(30) NOT NULL,
  `RISK_DESCRIPT` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`RISK_CLASS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`DANGER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`DANGER` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`DANGER` (
  `DANGER_CLASS` VARCHAR(30) NOT NULL,
  `DANGER_DESCRIPT` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`DANGER_CLASS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`SECON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`SECON` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`SECON` (
  `SECONDARY_CLASS` VARCHAR(30) NOT NULL,
  `SECONDARY_DESCRIPT` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`SECONDARY_CLASS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`ANOMALY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`ANOMALY` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`ANOMALY` (
  `ANOMALY_ID` INT(11) NOT NULL,
  `ANOMALY_NAME` VARCHAR(75) NOT NULL,
  `ANOMALY_DESCRIPT` VARCHAR(300) NULL DEFAULT NULL,
  `ANOMALY_CHARACTER` INT(11) NULL DEFAULT NULL,
  `ANOMALY_CONTAIN` VARCHAR(30) NOT NULL,
  `ANOMALY_RISK` VARCHAR(30) NULL DEFAULT NULL,
  `ANOMALY_DANGER` VARCHAR(30) NULL DEFAULT NULL,
  `ANOMALY_SECONDARY` VARCHAR(30) NULL DEFAULT NULL,
  `ANOMALY_CREATE_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ANOMALY_ID`),
  #INDEX `ANOMALY_CHARACTER` (`ANOMALY_CHARACTER` ASC) VISIBLE,
  #INDEX `ANOMALY_CONTAIN` (`ANOMALY_CONTAIN` ASC) VISIBLE,
  #INDEX `ANOMALY_RISK` (`ANOMALY_RISK` ASC) VISIBLE,
  #INDEX `ANOMALY_DANGER` (`ANOMALY_DANGER` ASC) VISIBLE,
  #INDEX `ANOMALY_SECONDARY` (`ANOMALY_SECONDARY` ASC) VISIBLE,
  #INDEX `ANOMALY_CREATE_ID` (`ANOMALY_CREATE_ID` ASC) VISIBLE,
  CONSTRAINT `ANOMALY_ibfk_1`
    FOREIGN KEY (`ANOMALY_CHARACTER`)
    REFERENCES `Final_Project`.`KNOWN_CHARACTERS` (`CHARACTER_ID`),
  CONSTRAINT `ANOMALY_ibfk_2`
    FOREIGN KEY (`ANOMALY_CONTAIN`)
    REFERENCES `Final_Project`.`CONTAIN` (`CONTAIN_CLASS`),
  CONSTRAINT `ANOMALY_ibfk_3`
    FOREIGN KEY (`ANOMALY_RISK`)
    REFERENCES `Final_Project`.`RISK` (`RISK_CLASS`),
  CONSTRAINT `ANOMALY_ibfk_4`
    FOREIGN KEY (`ANOMALY_DANGER`)
    REFERENCES `Final_Project`.`DANGER` (`DANGER_CLASS`),
  CONSTRAINT `ANOMALY_ibfk_5`
    FOREIGN KEY (`ANOMALY_SECONDARY`)
    REFERENCES `Final_Project`.`SECON` (`SECONDARY_CLASS`),
  CONSTRAINT `ANOMALY_ibfk_6`
    FOREIGN KEY (`ANOMALY_CREATE_ID`)
    REFERENCES `Final_Project`.`ANOMALY` (`ANOMALY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`ANOMALY_HIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`ANOMALY_HIST` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`ANOMALY_HIST` (
  `ANOMALY_ID` INT(11) NOT NULL,
  `ANOMALY_NAME` VARCHAR(30) NULL DEFAULT NULL,
  `ANOMALY_CHARACTER` INT(11) NULL DEFAULT NULL,
  `ANOMALY_CONTAIN` VARCHAR(30) NOT NULL,
  `ANOMALY_RISK` VARCHAR(30) NULL DEFAULT NULL,
  `ANOMALY_DANGER` VARCHAR(30) NULL DEFAULT NULL,
  `ANOMALY_SECONDARY` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`ANOMALY_ID`),
  CONSTRAINT `ANOMALY_HIST_ibfk_1`
    FOREIGN KEY (`ANOMALY_ID`)
    REFERENCES `Final_Project`.`ANOMALY` (`ANOMALY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`ARTICLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`ARTICLE` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`ARTICLE` (
  `ARTICLE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ARTICLE_TITLE` VARCHAR(100) NOT NULL,
  `ARTICLE_TYPE` INT(11) NOT NULL,
  `AUTHOR_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ARTICLE_ID`),
  #INDEX `AUTHOR_ID` (`AUTHOR_ID` ASC) VISIBLE,
  CONSTRAINT `ARTICLE_ibfk_1`
    FOREIGN KEY (`AUTHOR_ID`)
    REFERENCES `Final_Project`.`AUTHOR` (`AUTHOR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`SCP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`SCP` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`SCP` (
  `SCP_DESIGNATION` VARCHAR(8) NOT NULL,
  `SCP_SERIES` INT(11) NOT NULL,
  `ARTICLE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`SCP_DESIGNATION`),
  #INDEX `ARTICLE_ID` (`ARTICLE_ID` ASC) VISIBLE,
  CONSTRAINT `SCP_ibfk_1`
    FOREIGN KEY (`ARTICLE_ID`)
    REFERENCES `Final_Project`.`ARTICLE` (`ARTICLE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`ANOMALY_IN_SCP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`ANOMALY_IN_SCP` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`ANOMALY_IN_SCP` (
  `SCP_DESIGNATION` VARCHAR(8) NOT NULL,
  `ANOMALY_ID` INT(11) NOT NULL,
  PRIMARY KEY (`SCP_DESIGNATION`, `ANOMALY_ID`),
  #INDEX `ANOMALY_ID` (`ANOMALY_ID` ASC) VISIBLE,
  CONSTRAINT `ANOMALY_IN_SCP_ibfk_1`
    FOREIGN KEY (`SCP_DESIGNATION`)
    REFERENCES `Final_Project`.`SCP` (`SCP_DESIGNATION`),
  CONSTRAINT `ANOMALY_IN_SCP_ibfk_2`
    FOREIGN KEY (`ANOMALY_ID`)
    REFERENCES `Final_Project`.`ANOMALY` (`ANOMALY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`CHARACTER_HIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`CHARACTER_HIST` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`CHARACTER_HIST` (
  `CHARACTER_ID` INT(11) NOT NULL,
  `CHARACTER_NAME` VARCHAR(50) NOT NULL,
  `CHARACTER_ANOMALY` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CHARACTER_ID`),
  CONSTRAINT `CHARACTER_HIST_ibfk_1`
    FOREIGN KEY (`CHARACTER_ID`)
    REFERENCES `Final_Project`.`KNOWN_CHARACTERS` (`CHARACTER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`GOI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`GOI` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`GOI` (
  `GOI_NUM` INT(11) NOT NULL AUTO_INCREMENT,
  `GOI_NAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`GOI_NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`CHAR_IN_GOI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`CHAR_IN_GOI` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`CHAR_IN_GOI` (
  `CHARACTER_ID` INT(11) NOT NULL,
  `GOI_NUM` INT(11) NOT NULL,
  PRIMARY KEY (`CHARACTER_ID`, `GOI_NUM`),
  #INDEX `GOI_NUM` (`GOI_NUM` ASC) VISIBLE,
  CONSTRAINT `CHAR_IN_GOI_ibfk_1`
    FOREIGN KEY (`CHARACTER_ID`)
    REFERENCES `Final_Project`.`KNOWN_CHARACTERS` (`CHARACTER_ID`),
  CONSTRAINT `CHAR_IN_GOI_ibfk_2`
    FOREIGN KEY (`GOI_NUM`)
    REFERENCES `Final_Project`.`GOI` (`GOI_NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`GUIDE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`GUIDE` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`GUIDE` (
  `GUIDE_TYPE` VARCHAR(30) NULL DEFAULT NULL,
  `ARTICLE_ID` INT(11) NULL DEFAULT NULL,
  `GUIDE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`GUIDE_ID`),
  #INDEX `ARTICLE_ID` (`ARTICLE_ID` ASC) VISIBLE,
  CONSTRAINT `GUIDE_ibfk_1`
    FOREIGN KEY (`ARTICLE_ID`)
    REFERENCES `Final_Project`.`ARTICLE` (`ARTICLE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`SITE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`SITE` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`SITE` (
  `SITE_ID` INT(11) NOT NULL,
  `SITE_LOCATION` VARCHAR(30) NULL DEFAULT NULL,
  `ANOMALY_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`SITE_ID`),
  #INDEX `ANOMALY_ID` (`ANOMALY_ID` ASC) VISIBLE,
  CONSTRAINT `SITE_ibfk_1`
    FOREIGN KEY (`ANOMALY_ID`)
    REFERENCES `Final_Project`.`ANOMALY` (`ANOMALY_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`TALE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`TALE` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`TALE` (
  `CANON_ID` INT(11) NULL DEFAULT NULL,
  `CANON_TITLE` VARCHAR(30) NULL DEFAULT NULL,
  `TALE_GENRE` VARCHAR(30) NULL DEFAULT NULL,
  `TALE_ID` INT(11) NOT NULL,
  `ARTICLE_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`TALE_ID`),
  #INDEX `ARTICLE_ID` (`ARTICLE_ID` ASC) VISIBLE,
  CONSTRAINT `TALE_ibfk_1`
    FOREIGN KEY (`ARTICLE_ID`)
    REFERENCES `Final_Project`.`ARTICLE` (`ARTICLE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Final_Project`.`SITES_IN_TALES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Final_Project`.`SITES_IN_TALES` ;

CREATE TABLE IF NOT EXISTS `Final_Project`.`SITES_IN_TALES` (
  `SITE_ID` INT(11) NOT NULL,
  `TALE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`SITE_ID`, `TALE_ID`),
  #INDEX `TALE_ID` (`TALE_ID` ASC) VISIBLE,
  CONSTRAINT `SITES_IN_TALES_ibfk_1`
    FOREIGN KEY (`SITE_ID`)
    REFERENCES `Final_Project`.`SITE` (`SITE_ID`),
  CONSTRAINT `SITES_IN_TALES_ibfk_2`
    FOREIGN KEY (`TALE_ID`)
    REFERENCES `Final_Project`.`TALE` (`TALE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


#SET SQL_MODE=@OLD_SQL_MODE;
#SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
#SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;