# Elijah Sprung

#1
SELECT 
    SUM(LINE_UNITS) AS 'Total items sold on sale'
FROM
    PRODUCT
        JOIN
    LINE ON PRODUCT.P_CODE = LINE.P_CODE
WHERE
    PRODUCT.P_DISCOUNT > 0;

#2
SELECT 
    PRODUCT.P_DESCRIPT
FROM
    PRODUCT
WHERE
    PRODUCT.P_PRICE > (SELECT 
            (2 * AVG(PRODUCT.P_PRICE)) AS NUM
        FROM
            PRODUCT)
ORDER BY PRODUCT.P_QOH DESC;
    
#3
SELECT DISTINCT
    CUSTOMER.CUS_FNAME, CUSTOMER.CUS_LNAME
FROM
    CUSTOMER
        JOIN
    INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
        JOIN
    LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
        JOIN
    PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE
        JOIN
    VENDOR ON PRODUCT.V_CODE = VENDOR.V_CODE
WHERE
    V_STATE = 'TN' OR V_STATE = 'GA'
ORDER BY CUSTOMER.CUS_FNAME , CUSTOMER.CUS_LNAME;