#19
SELECT 
    SUM(NUM_INVOICES) AS 'Total Invoices',
    SUM(TOTAL_PURCHASES) AS 'Total Sales',
    MIN(TOTAL_PURCHASES) AS 'Minimum Customer Purchases',
    MAX(TOTAL_PURCHASES) AS 'Largest Customer Purchases',
    AVG(TOTAL_PURCHASES) AS 'Average Customer Purchases'
FROM
    (SELECT 
        CUS_CODE,
            COUNT(DISTINCT INVOICE.INV_NUMBER) AS NUM_INVOICES,
            SUM(LINE_UNITS * LINE_PRICE) AS TOTAL_PURCHASES
    FROM
        INVOICE
    JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
    GROUP BY CUS_CODE) AS DETAILS;

#20
SELECT DISTINCT
    CUSTOMER.CUS_CODE, CUSTOMER.CUS_BALANCE
FROM
    CUSTOMER
        JOIN
    INVOICE USING (CUS_CODE)
ORDER BY CUSTOMER.CUS_CODE;

#21
SELECT 
    MIN(CUSTOMER.CUS_BALANCE) AS 'Minimum Balance',
    MAX(CUSTOMER.CUS_BALANCE) AS 'Maximum Balance',
    AVG(CUSTOMER.CUS_BALANCE) AS 'Average Balance'
FROM
    CUSTOMER
WHERE
    CUSTOMER.CUS_CODE IN (SELECT 
            CUS_CODE
        FROM
            INVOICE);
    
#22
SELECT 
    SUM(CUSTOMER.CUS_BALANCE) AS 'Total Balances',
    MIN(CUSTOMER.CUS_BALANCE) AS 'Minimum Balance',
    MAX(CUSTOMER.CUS_BALANCE) AS 'Maximum Balance',
    AVG(CUSTOMER.CUS_BALANCE) AS 'Average Balance'
FROM
    CUSTOMER;
    
#23
SELECT 
    CUSTOMER.CUS_CODE, CUSTOMER.CUS_BALANCE
FROM
    CUSTOMER
WHERE
    CUSTOMER.CUS_CODE NOT IN (SELECT DISTINCT
            CUS_CODE
        FROM
            INVOICE);
            
#24
SELECT 
    SUM(CUSTOMER.CUS_BALANCE) AS 'Total Balances',
    MIN(CUSTOMER.CUS_BALANCE) AS 'Minimum Balance',
    MAX(CUSTOMER.CUS_BALANCE) AS 'Maximum Balance',
    AVG(CUSTOMER.CUS_BALANCE) AS 'Average Balance'
FROM
    CUSTOMER
WHERE
    CUSTOMER.CUS_CODE NOT IN (SELECT DISTINCT
            CUS_CODE
        FROM
            INVOICE);

#25
SELECT 
    PRODUCT.P_DESCRIPT,
    PRODUCT.P_QOH,
    PRODUCT.P_PRICE,
    PRODUCT.P_QOH * PRODUCT.P_PRICE AS SUBTOTAL
FROM
    PRODUCT
ORDER BY SUBTOTAL DESC;
    
#26
SELECT 
    SUM(PRODUCT.P_QOH * PRODUCT.P_PRICE) AS 'Total Value of Inventory'
FROM
    PRODUCT;