#9
SELECT 
    COUNT(DISTINCT INVOICE.INV_NUMBER) AS Invoices
FROM
    INVOICE;

#10
SELECT 
    COUNT(CUSTOMER.CUS_BALANCE)
FROM
    CUSTOMER
WHERE
    CUS_BALANCE > 500;

#11
SELECT 
    INVOICE.CUS_CODE,
    INVOICE.INV_NUMBER,
    INVOICE.INV_DATE,
    PRODUCT.P_DESCRIPT,
    LINE.LINE_UNITS,
    LINE.LINE_PRICE
FROM
    LINE
        JOIN
    PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE
        JOIN
    INVOICE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER
ORDER BY INVOICE.CUS_CODE , INVOICE.INV_NUMBER , PRODUCT.P_DESCRIPT;

#12
SELECT 
    INVOICE.CUS_CODE,
    INVOICE.INV_NUMBER,
    INVOICE.INV_DATE,
    PRODUCT.P_DESCRIPT,
    LINE.LINE_UNITS AS 'Units Bought',
    LINE.LINE_PRICE AS 'Unit Price',
    LINE.LINE_UNITS * LINE.LINE_PRICE AS 'Subtotal'
FROM
    LINE
        JOIN
    PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE
        JOIN
    INVOICE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER
ORDER BY INVOICE.CUS_CODE , INVOICE.INV_NUMBER , PRODUCT.P_DESCRIPT;

#13
SELECT 
    CUSTOMER.CUS_CODE,
    CUSTOMER.CUS_BALANCE,
    (SUM(LINE.LINE_UNITS * LINE.LINE_PRICE)) AS 'Total Purchases'
FROM
    CUSTOMER
		JOIN
	INVOICE USING (CUS_CODE)
		JOIN
	LINE USING (INV_NUMBER)
GROUP BY CUSTOMER.CUS_CODE;

#14
SELECT 
    CUSTOMER.CUS_CODE,
    CUSTOMER.CUS_BALANCE,
    (SUM(LINE.LINE_UNITS * LINE.LINE_PRICE)) AS 'Total Purchases',
    COUNT(*) AS 'Number of Purchases'
FROM
    CUSTOMER
		JOIN
	INVOICE USING (CUS_CODE)
		JOIN
	LINE USING (INV_NUMBER)
GROUP BY CUSTOMER.CUS_CODE;

#15
SELECT 
    CUSTOMER.CUS_CODE,
    CUSTOMER.CUS_BALANCE,
    (SUM(LINE.LINE_UNITS * LINE.LINE_PRICE)) AS 'Total Purchases',
    COUNT(*) AS 'Number of Purchases',
    AVG(LINE.LINE_UNITS * LINE.LINE_PRICE) AS 'Average Purchase Amount'
FROM
    CUSTOMER
		JOIN
	INVOICE USING (CUS_CODE)
		JOIN
	LINE USING (INV_NUMBER)
GROUP BY CUSTOMER.CUS_CODE;

#16
SELECT 
    LINE.INV_NUMBER,
    ROUND(SUM(LINE.LINE_UNITS * LINE.LINE_PRICE), 2) AS 'Invoice Total'
FROM
	LINE
GROUP BY LINE.INV_NUMBER;

#17
SELECT 
    CUSTOMER.CUS_CODE,
    INVOICE.INV_NUMBER,
    SUM(LINE_PRICE * LINE_UNITS) AS 'Invoice Total'
FROM
	CUSTOMER
		JOIN
	INVOICE USING (CUS_CODE)
		JOIN
	LINE USING (INV_NUMBER)
GROUP BY CUSTOMER.CUS_CODE, INVOICE.INV_NUMBER
ORDER BY CUSTOMER.CUS_CODE;

#18
SELECT
	DISTINCT INVOICE.CUS_CODE,
	COUNT(DISTINCT INVOICE.INV_NUMBER) AS 'Number of Invoices',
    SUM(LINE_PRICE * LINE_UNITS) AS 'Total Customer Purchases'
FROM
	CUSTOMER
		JOIN
	INVOICE USING (CUS_CODE)
		JOIN
	LINE USING (INV_NUMBER)
GROUP BY CUSTOMER.CUS_CODE
ORDER BY CUSTOMER.CUS_CODE;